build-job:
  stage: build
  script:
    - echo "hi $GITLAB_USER_LOGIN!"

test-job1:
  stage: test
  script:
    - echo "test"

test-job2:
  stage: test
  script:
    - echo "test2"
    - sleep 20

deploy-prod:
  stage: deploy
  script:
    - echo "deploy from $CI_COMMIT_BRANCH branch."


postman-tests:
  image: nikolaik/python-nodejs
  stage: test
  before_script:
    - npm install -g newman
    - cd backend
    - pip install -r requirements.txt
    - gunicorn wsgi:app -w 2 -b 0.0.0.0:8080 -t 60 &
    - cd ..
  script:
    - newman run postman_tests.json
