build-job:
  stage: build
  script:
    - echo "hi $GITLAB_USER_LOGIN!"

test-job1:
  stage: test
  script:
    - echo "test"

test-job2:
  stage: test
  script:
    - echo "test2"
    - sleep 20

deploy-prod:
  stage: deploy
  script:
    - echo "deploy from $CI_COMMIT_BRANCH branch."

